// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-reports.ts
import { createClient } from "npm:@supabase/supabase-js@^2.83.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_reports_default = defineTool({
  name: "list_reports",
  title: "List civic reports",
  description: "List civic reports visible to the signed-in user. Regular users see their own reports; admins and staff see all. Optionally filter by status and category.",
  inputSchema: {
    status: z.enum(["pending", "in_progress", "resolved", "rejected"]).optional().describe("Only return reports with this status."),
    category: z.enum(["pothole", "streetlight", "trash", "graffiti", "sidewalk", "drainage", "other"]).optional().describe("Only return reports with this category."),
    limit: z.number().int().min(1).max(100).optional().describe("Max rows to return (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, category, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const client = supabaseForUser(ctx);
    let query = client.from("reports").select("id, title, description, category, status, priority, latitude, longitude, address, created_at, updated_at, user_id, assigned_department").order("created_at", { ascending: false }).limit(limit ?? 25);
    if (status) query = query.eq("status", status);
    if (category) query = query.eq("category", category);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { reports: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-report.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.83.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_report_default = defineTool2({
  name: "get_report",
  title: "Get civic report",
  description: "Fetch a single civic report by id. Access is enforced by row-level security.",
  inputSchema: {
    id: z2.string().uuid().describe("The report id (uuid).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser2(ctx).from("reports").select("*").eq("id", id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Report not found or access denied." }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { report: data }
    };
  }
});

// src/lib/mcp/tools/create-report.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.83.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var create_report_default = defineTool3({
  name: "create_report",
  title: "Submit a civic report",
  description: "Submit a new civic issue report (pothole, streetlight, trash, etc.) as the signed-in user. Optionally include latitude/longitude and an address.",
  inputSchema: {
    title: z3.string().trim().min(5).max(100).describe("Short title for the issue."),
    description: z3.string().trim().min(10).max(1e3).describe("Details about the issue."),
    category: z3.enum(["pothole", "streetlight", "trash", "graffiti", "sidewalk", "drainage", "other"]).describe("Issue category."),
    priority: z3.enum(["low", "medium", "high", "urgent"]).optional().describe("Priority (default medium)."),
    latitude: z3.number().min(-90).max(90).optional().describe("Latitude of the issue location."),
    longitude: z3.number().min(-180).max(180).optional().describe("Longitude of the issue location."),
    address: z3.string().trim().max(300).optional().describe("Human-readable address.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ title, description, category, priority, latitude, longitude, address }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser3(ctx).from("reports").insert({
      user_id: ctx.getUserId(),
      title,
      description,
      category,
      priority: priority ?? "medium",
      latitude,
      longitude,
      address
    }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Report created (id ${data.id}).` }],
      structuredContent: { report: data }
    };
  }
});

// src/lib/mcp/tools/update-report-status.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.83.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^3.25.76";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var update_report_status_default = defineTool4({
  name: "update_report_status",
  title: "Update report status",
  description: "Update the status of a civic report. Restricted to admin/staff users; row-level security enforces this on the server.",
  inputSchema: {
    id: z4.string().uuid().describe("The report id to update."),
    status: z4.enum(["pending", "in_progress", "resolved", "rejected"]).describe("The new status for the report."),
    assigned_department: z4.string().trim().max(100).optional().describe("Optional department to assign this report to.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ id, status, assigned_department }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const client = supabaseForUser4(ctx);
    const { data: roles, error: rolesError } = await client.from("user_roles").select("role").eq("user_id", ctx.getUserId());
    if (rolesError) return { content: [{ type: "text", text: rolesError.message }], isError: true };
    const isAdmin = (roles ?? []).some((r) => r.role === "admin" || r.role === "staff");
    if (!isAdmin) {
      return {
        content: [{ type: "text", text: "Only admin or staff users can update report status." }],
        isError: true
      };
    }
    const update = { status };
    if (assigned_department !== void 0) update.assigned_department = assigned_department;
    const { data, error } = await client.from("reports").update(update).eq("id", id).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Report ${id} updated to ${status}.` }],
      structuredContent: { report: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "xhcioifvackxsfgbhgpa";
var mcp_default = defineMcp({
  name: "civic-connect-mcp",
  title: "Civic Connect",
  version: "0.1.0",
  instructions: "Tools for Civic Connect, a civic issue reporting platform. Use `list_reports` to browse reports the signed-in user can see, `get_report` for a single report by id, `create_report` to submit a new civic issue, and `update_report_status` (admin/staff only) to move a report through pending \u2192 in_progress \u2192 resolved/rejected.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_reports_default, get_report_default, create_report_default, update_report_status_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
